version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    restart: unless-stopped
    ports:
      - "$RABBITMQ_PORT:5672"
      - "$RABBITMQ_MANAGEMENT_PORT:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    hostname: rabbitmq
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mongo:/data/db
    ports:
      - "$MONGO_PORT:27017"

volumes:
  rabbitmq:
  mongo:
