version: '2'

services:
  agent:
    extends:
      file: docker-compose-app.yml
      service: app
    environment:
      - APP=agent
    depends_on:
      - collector
  collector:
    extends:
      file: docker-compose-app.yml
      service: app
    environment:
      - APP=collector
    depends_on:
        - queuer
    ports:
      - "50051:50051"
  queuer:
    env_file: .env
    image: rabbitmq:3.7.3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "5672"
    volumes:
      - /conlog/data/rabbitmq:/var/lib/rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
