services:
    api.event_controller:
        class: Array51\AgendaBundle\Controller\EventController
        arguments: [@api.event_service]

    api.calendar_controller_v1_1:
        class: Array51\AgendaBundle\Controller\V1_1\CalendarController
        arguments: [@api.calendar_service]