services:
    api.base_service:
        class: Array51\AgendaBundle\Service\AbstractBaseService
        arguments: [@service_container]
        abstract: true

    api.event_service:
        class: Array51\AgendaBundle\Service\EventService
        calls:
          - [setFormService, [@api.form_service]]
          - [setEventRepository, [@=service('doctrine.orm.default_entity_manager').getRepository('DataBundle:Event')]]
        parent: api.base_service

    api.calendar_service:
        class: Array51\AgendaBundle\Service\CalendarService
        calls:
          - [setEventRepository, [@=service('doctrine.orm.default_entity_manager').getRepository('DataBundle:Event')]]
        parent: api.base_service

    api.form_service:
        class: Array51\AgendaBundle\Service\FormService
        calls:
          - [setFormFactory, [@form.factory]]